apiVersion: apps/v1
kind: Deployment

metadata:
  name: analysis-agent

spec:
  replicas: 1

  selector:
    matchLabels:
      app: analysis-agent

  template:

    metadata:
      labels:
        app: analysis-agent

    spec:

      containers:

        - name: analysis-agent

          image: yklee2002/analysis-agent

          imagePullPolicy: Always

          ports:

            - containerPort: 8000


          env:

            - name: DB_HOST
              value: "mysql"

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: "analytics"

            - name: DB_USER
              value: "root"

            - name: DB_PASSWORD
              value: "root1234"


          resources:

            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "1000m"
              memory: "512Mi"


          readinessProbe:

            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 10


          livenessProbe:

            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 20


---

apiVersion: v1
kind: Service

metadata:
  name: analysis-agent

spec:

  selector:
    app: analysis-agent

  type: NodePort

  ports:

    - name: http

      port: 8000

      targetPort: 8000

      nodePort: 30800