apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-simulator

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-simulator

  template:
    metadata:
      labels:
        app: order-simulator

    spec:
      containers:

        - name: order-simulator

          image: yklee2002/order-simulator

          imagePullPolicy: Always

          env:
            - name: DB_HOST
              value: "mysql"

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: "orderdb"

            - name: DB_USER
              value: "root"

            - name: DB_PASSWORD
              value: "root1234"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"